estate2/estate2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("houses.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

estate2/houses/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index,name="home"),
    path('property/<int:id>', views.single,name="single"),
    #path('properties', views.propertiesView.as_view(),name="properties"),
    path('properties', views.list_properties,name="properties"),
    path('about', views.about,name="about"),

    path('add_house', views.add_house,name="add_house"),

    path('update_property/<int:pk>', views.update_property.as_view(),name="update_property"),

    path('delete_property/<int:pk>', views.delete_property.as_view(),name="delete_property"),

    path('userlogin', views.userlogin,name="userlogin"),
    path('userregister', views.userregister,name="userregister"),
    path('userlogout', views.userlogout,name="userlogout"),
    path('Profile', views.Profile,name="Profile"),
    path('messages', views.messages,name="messages"),


    path('search-for', views.search_for,name="search_for"),
    path('get-inquiry', views.get_inquiry,name="get_inquiry"),
    path('show-all-inquiry', views.show_all_inquiry,name="show_all_inquiry"),

    path('write-msg', views.write_msg,name="write_msg"),

    path('show-place/<str:place>', views.show_place,name="show_place"),
    path('show-type/<str:type_of_place>', views.show_type,name="show_type"),

    path('show_all_projects', views.show_all_projects,name="show_all_projects"),
    path('show_all_companies', views.show_all_companies,name="show_all_companies"),

    path('show_single_company/<int:id>', views.show_single_company,name="show_single_company"),
    path('show_single_project/<int:id>', views.show_single_project,name="show_single_project"),

    path('add_project', views.add_project,name="add_project"),
    path('add_company', views.add_company,name="add_company"),

    path('get_type_count', views.get_type_count,name="get_type_count"),
    path('get_type_only/<str:type>', views.get_type_only,name="get_type_only"),

    path('delete_msg/<int:id>', views.delete_msg,name="delete_msg"),
    path('delete_inquiry/<int:id>', views.delete_inquiry,name="delete_inquiry"),

    path('edit_footer/<int:pk>', views.edit_footer.as_view(),name="edit_footer"),
    path('edit_msg/<int:pk>', views.edit_msg.as_view(),name="edit_msg"),
    path('edit_inquiry/<int:pk>', views.edit_inquiry.as_view(),name="edit_inquiry"),
    path('edit_about/<int:pk>', views.edit_about.as_view(),name="edit_about"),
]

estate2/houses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
# Create your models here.

choices2 = (('Any', 'Any'),
                ('Building', 'Building'),
                ('Clinic', 'Clinic'),
                ('Food & Beverage', 'Food & Beverage'),
                ('Office', 'Office'),
                ('Retail', 'Retail'),
                ('Shop', 'Shop'),
                ('Store', 'Store'),
                ('Apartment', 'Apartment'),
                ('Chalet', 'Chalet'),
                ('Condo', 'Condo'),
                ('Duplex', 'Duplex'),
                ('Ground Floor', 'Ground Floor'),
                ('iVilla', 'iVilla'),
                ('Multi Family Home', 'Multi Family Home'),
                ('Penthouse', 'Penthouse'),
                ('S Villa', 'S Villa'),
                ('Serviced Apartment', 'Serviced Apartment'),
                ('Single Family Home', 'Single Family Home'),
                ('Sky Loft', 'Sky Loft'),
                ('Studio', 'Studio'),
                ('Townhouse', 'Townhouse'),
                ('Twin House', 'Twin House'),
                ('Villa', 'Villa'))
choices3 = (("Ain Shokana","Ain Shokana"),
                ("Ain Sokhna","Ain Sokhna"),
                ("Alexandria","Alexandria"),
                ("East Cairo","East Cairo"),
                ("Mostakbal City","Mostakbal City"),
                ("New Cairo","New Cairo"),
                ("New Capital","New Capital"),
                ("North Coast","North Coast"),
                ("Sheik Zayed","Sheik Zayed"),
                ("West Cairo","West Cairo"),
                ("6th of October","6th of October"),
                ("New Zayed","New Zayed"))

class Amenity(models.Model):
    status_choices = (
        (_("Balcony"), _("Balcony")),
        (_("Cable TV"), _("Cable TV")),
        (_("Internet"), _("Internet")),
        (_("Tennis Courts"), _("Tennis Courts")),
        (_("Parking"), _("Parking")),
    )
    name = models.CharField(max_length=100,choices=status_choices,verbose_name=_("name"))
    def __str__(self):
        return f"{self.name}"

class Image_of_house(models.Model):
    img = models.ImageField(upload_to="images")
    house = models.ForeignKey("House",on_delete=models.CASCADE,related_name="other_imgs")
    def __str__(self):
        return f"image({self.img})"
"""
class Agent(models.Model):
    name = models.CharField(_("name"),max_length=50)
    age = models.IntegerField(_("age"),)
    email = models.EmailField(_("email"),null=True,blank=True)
    phone = models.CharField(_("phone"),max_length=50,null=True,blank=True)
    skype = models.CharField(_("skype"),null=True,blank=True,max_length=100)
    img = models.ImageField(_("img"),null=True,blank=True,upload_to="images")
    def __str__(self):
        return f"agent ({self.name})"
"""
class House(models.Model):
    status_choices = (
        (_("sale"), _("sale")),
        (_("rent"), _("rent")),
    )

    img = models.ImageField(_("img"),upload_to="images")
    type = models.CharField(max_length=50,choices=choices2,default="Apartment")
    address = models.CharField(_("address"),max_length=50)
    location = models.CharField(max_length=50,choices=choices3,null=True,blank=True)
    status = models.CharField(_("status"),max_length=100,choices=status_choices)
    area = models.IntegerField(_("area"),)
    beds = models.IntegerField(_("beds"),)
    bathrooms = models.IntegerField(_("bathrooms"),)
    garages = models.IntegerField(_("garages"),)
    price = models.IntegerField(_("price"),)
    #agent = models.ForeignKey(Agent,on_delete=models.CASCADE,verbose_name=_("agent"))
    description = models.TextField(_("description"),)
    amenities = models.ManyToManyField(Amenity,verbose_name=_("amenities"))
    company = models.ForeignKey('Company',on_delete=models.CASCADE,blank=True,null=True)
    project = models.ForeignKey('Project',on_delete=models.CASCADE,blank=True,null=True)
    number_of_installments = models.IntegerField(default=1)
    time_of_delivery = models.DateTimeField(null=True,blank=True)
    in_advance_price = models.IntegerField(default=0)
    def __str__(self):
        return f"House ({self.id})==>{self.price}EGP"




class Company(models.Model):
    name = models.CharField(max_length=500)
    location = models.CharField(max_length=500,choices=choices3,default='Ain Shokana')
    logo = models.ImageField(upload_to="images",default='houses/real_estate_logo.jpg')
    def __str__(self):
        return f"{self.name}"

class Project(models.Model):
    name = models.CharField(max_length=500)
    company = models.ForeignKey(Company,on_delete=models.CASCADE,null=True,blank=True)
    type = models.CharField(max_length=50, choices=choices2, default="Apartment")
    location = models.CharField(max_length=500, choices=choices3,default='Ain Shokana')
    number_of_units = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.name}"



class Message(models.Model):
    user_name = models.CharField(max_length=50,verbose_name=_("user_name"))
    content = models.TextField(verbose_name=_("content"))
    email = models.EmailField(verbose_name=_("email"))
    #agent = models.ForeignKey(Agent,on_delete=models.CASCADE,verbose_name=_("agent"),null=True,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    date = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=30,null=True,blank=True)
    project = models.ForeignKey(Project,on_delete=models.CASCADE,blank=True,null=True)
    def __str__(self):
        return f"message from agent({self.user_name})"

class Inquiry(models.Model):
    choices1 = (('buyer','buyer'),
                ('seller','seller'))
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=User.objects.all()[0].id)
    buyer_or_seller = models.CharField(max_length=20,choices=choices1,default='buyer')
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = models.CharField(max_length=30)
    location = models.CharField(max_length=50, choices=choices3, null=True, blank=True,default='Ain Shokana')
    type = models.CharField(max_length=50, choices=choices2, default="Apartment")
    max_price = models.IntegerField()
    min_size = models.IntegerField()
    beds = models.IntegerField()
    bathrooms = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True,null=True,blank=True)

class footer_text(models.Model):
    address = models.CharField(max_length=100,default='Head Office | Building 259, 2nd Sector, North 90th St. New Cairo, Cairo - Egypt.')
    phone = models.CharField(max_length=50,default='Phone . contact@example.com')
    email = models.CharField(max_length=50,default='Email . +54 356 945234')
    user = models.ForeignKey(User,on_delete=models.CASCADE)

class about(models.Model):
    first_paragraph = models.CharField(max_length=100,default='We Do Great Design For Creative Folks')
    img1 = models.ImageField(upload_to="images",null=True,blank=True)
    name1 = models.CharField(max_length=50,default='red winners')
    img2 = models.ImageField(upload_to="images",null=True,blank=True)
    since_when = models.CharField(max_length=50,default='Since 2017')
    description1 = models.TextField(default="Enter description 1 here")
    description1 = models.TextField(default="Enter description 2 here")
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=1)

estate2/houses/templates/houses/about.html
{% extends 'houses/base.html' %}
{% load static %}

{% block title %}About Us{% endblock %}

{% block content %}
  <main id="main">

    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
          <div>
              {% if request.user.is_authenticated %}
                <a href="{% url 'edit_about' 1 %}" class="btn btn-success">Edit</a>
              {% endif %}
            </div>
            <div class="title-single-box">
              {% if request.user.is_authenticated %}
              <h1 class="title-single">{{request.user.about_set.all.0.first_paragraph}}</h1>
              {% else %}
              <h1 class="title-single">We Do Great Design For Creative Folks</h1>
              {% endif %}
            </div>

          </div>
        </div>
      </div>
    </section><!-- End Intro Single-->

    <!-- ======= About Section ======= -->
    <section class="section-about">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 position-relative">

            <div class="about-img-box">
              {% if request.user.about_set.all.0.img1 %}
              <img src="{{request.user.about_set.all.0.img1.url}}" alt="" class="img-fluid">
              {% else %}
               <img src="{% static 'houses/assets/img/slide-about-1.jpg' %}" alt="" class="img-fluid">
              {% endif %}
            </div>

            <div class="sinse-box">
              {% if request.user.is_authenticated %}
              <h3 class="sinse-title">{{request.user.about_set.all.0.name1}}</h3>
                {% else %}
              <h3 class="sinse-title">red winners</h3>
                {% endif %}
                <span></span>
              {% if request.user.is_authenticated %}
                <br> {{request.user.about_set.all.0.since_when}}
              {% else %}
                <br> Since 2017
              {% endif %}
            </div>

          </div>
          <div class="col-md-12 section-t8 position-relative">
            <div class="row">
              <div class="col-md-6 col-lg-5">
                {% if request.user.about_set.all.0.img2 %}
                <img src="{{request.user.about_set.all.0.img2.url}}" alt="" class="img-fluid">
                {% else %}
                <img src="{% static 'houses/assets/img/about-2.jpg' %}" alt="" class="img-fluid">
                {% endif %}
              </div>
              <div class="col-lg-2  d-none d-lg-block position-relative">
                <div class="title-vertical d-flex justify-content-start">
                  <span>{{request.user.about_set.all.0.name1}} Exclusive Property</span>
                </div>
              </div>
              <div class="col-md-6 col-lg-5 section-md-t3">
                <div class="title-box-d">
                </div>
                <p class="color-text-a">{{request.user.about_set.all.0.description1}}
                  Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus magna justo, lacinia eget
                  consectetur sed, convallis
                  at tellus. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Vestibulum
                  ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit
                  neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.
                </p>
                <p class="color-text-a">{{request.user.about_set.all.0.description2}}
                  Sed porttitor lectus nibh. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.
                  Mauris blandit aliquet
                  elit, eget tincidunt nibh pulvinar a. Vivamus magna justo, lacinia eget consectetur sed,
                  convallis at tellus.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- =======Team Section ======= -->

  </main><!-- End #main -->

{% endblock %}

estate2/houses/templates/houses/add_company.html
{% extends 'houses/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}Add a new Company{% endblock %}

{% block content %}


<form method="POST" enctype="multipart/form-data" style=";margin:70px 30px;">
    {% csrf_token %}
    {{form.as_p}}
    <input style="width:130px;height:40px;margin:13px 15px;" type="submit">
</form>

{% endblock %}

estate2/houses/templates/houses/add_project.html
{% extends 'houses/base.html' %}
{% load static %}
{% load i18n %}
{% block title %}Add a new Project{% endblock %}

{% block content %}


<form method="POST" enctype="multipart/form-data" style=";margin:70px 30px;">
    {% csrf_token %}
    {{form.as_p}}
    <input style="width:130px;height:40px;margin:13px 15px;" type="submit">
</form>

{% endblock %}

estate2/houses/templates/houses/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}red winners Bootstrap Template - Index{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'houses/assets/img/letter-r.png' %}" rel="icon">
  <link href="{% static 'houses/assets/img/letter-r.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'houses/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'houses/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'houses/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'houses/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'houses/assets/css/style.css' %}" rel="stylesheet">
    <style>
    @keyframes msg{
        0%{background-color:white;color:black;}
        50%{background-color:#2eca6a;color:white;}
        100%{background-color:white;color:black;}
    }
    #msg_me{
        animation-name:msg<remove this>;
        animation-duration:1s;
        animation-fill-mode:forwards;
        animation-iteration-count:infinite;
    }

    {% block css %}

    {% endblock %}
    </style>
  <!-- =======================================================
  * Template Name: EstateAgency - v4.7.0
  * Template URL: https://bootstrapmade.com/real-estate-agency-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
{% if request.path == "/write-msg" %}
{% else %}

<a id="msg_me" style="font-size:35px;border-radius:50%;position:fixed;bottom:10px;left:1144px;z-index:2000;" class="bi bi-chat-left-dots btn btn-danger" href="{% url 'write_msg' %}"></a>

<a id="leave_a_msg" style="border-radius:20%;position:fixed;bottom:60px;left:990px;z-index:1010;" class="btn btn-outline-danger" href="{% url 'write_msg' %}">Leave a message</a>
{% endif %}

  <!-- ======= Header/Navbar ======= -->
  <nav class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top" style="height:70px;">
    <div class="container" style="position:relative;left:0px;">
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDefault" aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>

      <a class="navbar-brand text-brand" style="position:fixed;top:0px;right:0px;" href="{% url 'home' %}">
          <img style="width:100px;height:50px;" src="{% static 'houses/real_estate_logo.jpg' %}">
      </a>

      <div style="background-color:white;" class="navbar-collapse collapse justify-content-center" id="navbarDefault">
        <ul class="navbar-nav">
          {% if request.path == "/" %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          {% endif %}
{% if user.is_authenticated %}
            {% if request.path == "/show-all-inquiry" %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'show_all_inquiry' %}">
              Inquiries(<span style="color:red;">{{request.user.inquiry_set.count}}</span>)
            </a>
          </li>
            {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'show_all_inquiry' %}">
              Inquiries(<span style="color:red;">{{request.user.inquiry_set.count}}</span>)
            </a>
          </li>
            {% endif %}
 <!--
{% if request.user %}
          {% if request.path == "/Profile" %}
          <li class="nav-item active">
            <a class="nav-link" style="font-weight:400;">
              Logged in as(<span style="color:red;">{{request.user.username}}</span>)
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" style="font-weight:400;">
               Logged in as(<span style="color:red;">{{request.user.username}}</span>)
            </a>
          </li>
          {% endif %}
-->
          {% if request.path == "/messages" %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'messages' %}">Messages(<span style="color:red;">{{request.user.message_set.count}}</span>)</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'messages' %}">Messages(<span style="color:red;">{{request.user.message_set.count}}</span>)</a>
          </li>
          {% endif %}
{% endif %}
{% endif %}
          {% if request.path == "/about" %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">{% translate "About" %}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">{% translate "About" %}</a>
          </li>
          {% endif %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% translate "Pages" %}</a>
            <div class="dropdown-menu">
              <a class="dropdown-item " href="{% url 'properties' %}">{% translate "Properties" %}</a>
              <a class="dropdown-item " href="{% url 'show_all_projects' %}">Projects</a>
              <a class="dropdown-item " href="{% url 'show_all_companies' %}">Developers</a>
              <a class="dropdown-item " href="{% url 'get_type_count' %}">Types</a>
            </div>
          </li>
        <!--
          <li class="nav-item">
            <a class="nav-link " href="contact.html">Contact</a>
          </li>
          -->
        </ul>
      </div>


    </div>
  </nav><!-- End Header/Navbar -->


 {% block content %} {% endblock %}


  <!-- ======= Footer ======= -->
  <section class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">red winners</h3>
            </div>
            <!--footer-->
            {% if request.user.is_authenticated %}
            <a href="{% url 'edit_footer' 1 %}" class="btn btn-success">Edit</a>
            {% endif %}
            <div class="w-body-a">
              <p class="w-text-a color-text-a">
                {% if request.user.is_authenticated %}
                  {{request.user.footer_text_set.all.0.address}}
                {% else %}
                  custom address | Building 259, 2nd Sector, North 90th St. New Cairo, Cairo - Egypt.
                {% endif %}
              </p>
            </div>
            <div class="w-footer-a">
              <ul class="list-unstyled">
                <li class="color-a">
                  {% if request.user.is_authenticated %}
                  <span class="color-text-a">Phone. {{request.user.footer_text_set.all.0.phone}}</span>
                  {% else %}
                  <span class="color-text-a">Phone. contact@example.com</span>
                  {% endif %}
                </li>
                <li class="color-a">
                  {% if request.user.is_authenticated %}
                  <span class="color-text-a">Email. {{request.user.footer_text_set.all.0.email}}</span>
                  {% else %}
                  <span class="color-text-a">Email. +54 356 945234</span>
                  {% endif %}
                </li>
              </ul>
            </div>

          </div>
        </div>

      </div>
    </div>
  </section>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="nav-footer">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="{% url 'home' %}">Home</a>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'about' %}">About</a>
              </li>
              <li class="list-inline-item">
                <a href="{% url 'properties' %}">Property</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
            </ul>
          </nav>
          <div class="socials-a">
            <ul class="list-inline">
              <li class="list-inline-item">
                <a href="https://www.facebook.com/">
                  <i class="bi bi-facebook" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.twitter.com/">
                  <i class="bi bi-twitter" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.instagram.com/">
                  <i class="bi bi-instagram" aria-hidden="true"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.linkedin.com/">
                  <i class="bi bi-linkedin" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="copyright-footer">
            <p class="copyright color-text-a">
              &copy; Copyright
              <span class="color-a">red winners</span> All Rights Reserved.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <div id="preloader"></div>
  <a href="#"  class="btn btn-danger back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'houses/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'houses/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'houses/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'houses/assets/js/main.js' %}"></script>

</body>

</html>

estate2/houses/templates/houses/show_companies.html
{% extends 'houses/base.html' %}
{% load static %}

{% block title %}Show All Companies{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
<div style="margin:80px 0;">
  <a class="btn btn-outline-danger" href="{% url 'add_company' %}">Add a new Company</a>
</div>
{% endif %}
  <main id="main" style="margin:100px 0;">
<div style="container;display:flex;justify-content:center;align-items:center;">

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Location</th>
      <th scope="col">number of units</th>
    </tr>
  </thead>
  <tbody>
    {% for company in all_companies %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td><img style="width:50px;height:50px;" src="{{company.logo.url}}"><a style="color:blue;" href="{% url 'show_single_company' company.id %}">{{company.name}}</a></td>
      <td>{{company.location}}</td>
      <td>{{company.house_set.all.count}}</td>
      <td></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
  </main><!-- End #main -->

{% endblock %}

estate2/houses/templates/houses/show_projects.html
{% extends 'houses/base.html' %}
{% load static %}

{% block title %}Search Results{% endblock %}

{% block content %}
{% if request.user.is_authenticated %}
<div style="margin:80px 0;">
  <a class="btn btn-outline-danger" href="{% url 'add_project' %}">Add a new Project</a>
</div>
{% endif %}
  <main id="main" style="margin:100px 0;">
<div style="container;display:flex;justify-content:center;align-items:center;">

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">developer</th>
      <th scope="col">Type</th>
      <th scope="col">Location</th>
      <th scope="col">number of units</th>
    </tr>
  </thead>
  <tbody><!-- position:relative;top:50px;  -->
    {% for project in all_projects %}
    <tr style="position:relative">
      <th scope="row">{{forloop.counter}}</th>
      <td><a style="color:blue;" href="{% url 'show_single_project' project.id %}">{{project.name}}</a></td>
      <td><a style="color:blue;" href="{% url 'show_single_company' project.company.id %}"><div><img style="width:60%;height:50px;" src="{{project.company.logo.url}}"></div>{{project.company}}</a></td>
      <td>{{project.type}}</td>
      <td>{{project.location}}</td>
      <td>{{project.house_set.all.count}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
  </main><!-- End #main -->

{% endblock %}

estate2/houses/templates/houses/write_new_message.html
{% extends 'houses/base.html' %}
{% load static %}

{% block title %}Search Results{% endblock %}

{% block content %}


  <main id="main" style="margin:100px 0;">
<div style="display:flex;justify-content:center;align-items:center;">
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button value="submit" style="position:absolute;left:45%;width:130px;height:40px;margin:13px 15px;">Submit</button>
  </form>
</div>
  </main><!-- End #main -->

{% endblock %}